;;; generated by ../../BootSetup/BootSetup.rb (2017-12-15 19:07:16 +0100)

	.include "ports.atmega8.inc" 	

;;; ========================================================================
;;; Interrupt Table
;;; ========================================================================

	.org  0                   	
	rjmp  RESET               	
	reti                      	; INT0
	reti                      	; INT1
	reti                      	; Timer2 Compare
	reti                      	; Timer2 Overflow
	reti                      	; Timer1 Capture
	reti                      	; Timer1 Compare A
	reti                      	; Timer1 Compare B
	reti                      	; Timer1 Overflow
	reti                      	; Timer0 Overflow
	reti                      	; SPI
	reti                      	; USART RX Complete
	reti                      	; USART UDR Empty
	reti                      	; USART TX Complete
	reti                      	; ADC Conversion Complete
	reti                      	; EEPROM Ready
	reti                      	; Analog Compare
	reti                      	; 2-wire Serial Interface
	reti                      	; Store Program Memory Ready

;;; ========================================================================
;;; Boot Setup
;;; ========================================================================

RESET:	ldi   r16, 0x00           	; 0
	out   TWBR, r16           	; TWI Bit Rate Register [0x00]
	out   TWSR, r16           	; TWI Status Register [0x01]
	ldi   r17, 0xfe           	; 254
	out   TWAR, r17           	; TWI (Slave) Address Register [0x02]
	out   UBRRL, r16          	; USART Baud Rate Register Low [0x09]
	out   UCSRB, r16          	; USART Control and Status Register B [0x0a]
	out   UCSRA, r16          	; USART Control and Status Register A [0x0b]
	out   SPCR, r16           	; SPI Control Register [0x0d]
	out   SPSR, r16           	; SPI Status Register [0x0e]
	out   DDRD, r16           	; Port D Data Direction Register [0x11]
	out   PORTD, r16          	; Port D Data Register [0x12]
	out   DDRC, r16           	; Port C Data Direction Register [0x14]
	out   PORTC, r16          	; Port C Data Register [0x15]
	out   DDRB, r16           	; Port B Data Direction Register [0x17]
	out   PORTB, r16          	; Port B Data Register [0x18]
	out   UBRRH, r16          	; USART Baud Rate Register High [0x20]
	ldi   r17, 0x86           	; 134
	out   UCSRC, r17          	; USART Control and Status Register 0 C [0x20]
	out   TCNT0, r16          	; Timer/Counter Register [0x32]
	out   TCCR0, r16          	; Timer/Counter Control Register [0x33]
	out   MCUCR, r16          	; MCU Control Register [0x35]
	out   TWCR, r16           	; TWI Control Register [0x36]
	out   TIFR, r16           	; Timer/Counter Interrupt Flag Register [0x38]
	out   TIMSK, r16          	; Timer/Counter Interrupt Mask Register [0x39]
	out   GICR, r16           	; General Interrupt Control Register [0x3b]

	ldi   r17, lo8(RAMEND)    	
	out   SPL, r17            	; Stack Pointer Low [0x3d]
	ldi   r17, hi8(RAMEND)    	
	out   SPH, r17            	; Stack Pointer High [0x3e]
	out   SREG, r16           	; Status Register [0x3f]

	rjmp  Main                	

;;; generated by ../../BootSetup/BootSetup.rb (2017-12-15 19:07:16 +0100)
